# Form implementation generated from reading ui file 'd:\code\python\pyqt\yolo\source\ui\graphic_cls.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(544, 448)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.lineEdit_locate = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_locate.setObjectName("lineEdit_locate")
        self.verticalLayout_2.addWidget(self.lineEdit_locate)
        self.pushButton_locate = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_locate.setObjectName("pushButton_locate")
        self.verticalLayout_2.addWidget(self.pushButton_locate)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(3, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.listWidget_src = QtWidgets.QListWidget(parent=Dialog)
        self.listWidget_src.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.MultiSelection)
        self.listWidget_src.setSelectionRectVisible(False)
        self.listWidget_src.setObjectName("listWidget_src")
        self.horizontalLayout.addWidget(self.listWidget_src)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.pushButton_all = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_all.setObjectName("pushButton_all")
        self.verticalLayout_3.addWidget(self.pushButton_all)
        self.pushButton_cls_ok = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_cls_ok.setObjectName("pushButton_cls_ok")
        self.verticalLayout_3.addWidget(self.pushButton_cls_ok)
        self.pushButton_cls_no = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_cls_no.setObjectName("pushButton_cls_no")
        self.verticalLayout_3.addWidget(self.pushButton_cls_no)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.listWidget_tgt = QtWidgets.QListWidget(parent=Dialog)
        self.listWidget_tgt.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.listWidget_tgt.setObjectName("listWidget_tgt")
        self.horizontalLayout.addWidget(self.listWidget_tgt)
        self.pushButton_clr = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_clr.setObjectName("pushButton_clr")
        self.horizontalLayout.addWidget(self.pushButton_clr)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lineEdit_locate.setPlaceholderText(_translate("Dialog", "寻找指定标签"))
        self.pushButton_locate.setText(_translate("Dialog", "确定"))
        self.pushButton_all.setText(_translate("Dialog", "(取消)全选"))
        self.pushButton_cls_ok.setText(_translate("Dialog", "确定"))
        self.pushButton_cls_no.setText(_translate("Dialog", "取消"))
        self.pushButton_clr.setText(_translate("Dialog", "清除所选"))
